[package]
name = "ttv"
version = "0.1.0"
authors = ["skbaek <seulkeebaek@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tptp = "0.23.0"

[dependencies.basic]
path = "../basic"
